### ISSUE TITLE
Problem with example (sqlite3.ProgrammingError)

### ISSUE THREAD

**Issue by pavvel1610** [desbma/GoogleSpeech#24]
Hello since about 5 days I have a problem with this library, it's not working at all. Some sqlite3 error is printed even for the simplest example. I've tried to reinstall the sqllite library but it didn't help. Anyone has the same error?

google_speech -l en "Hello $USER, it is $(date)"
Traceback (most recent call last):
  File "/usr/bin/google_speech", line 11, in <module>
    load_entry_point('google-speech==1.1.0', 'console_scripts', 'google_speech')()
  File "/usr/lib/python3.8/site-packages/google_speech/__init__.py", line 319, in cl_main
    speech.play(args.sox_effects)
  File "/usr/lib/python3.8/site-packages/google_speech/__init__.py", line 129, in play
    segments = list(self)
  File "/usr/lib/python3.8/site-packages/google_speech/__init__.py", line 89, in __next__
    yield SpeechSegment(segment, self.lang, segment_num, len(segments))
  File "/usr/lib/python3.8/site-packages/google_speech/__init__.py", line 174, in __init__
    __class__.cache = web_cache.ThreadedWebCache(db_filepath,
  File "/usr/lib/python3.8/site-packages/web_cache/__init__.py", line 334, in __init__
    raise e
  File "/usr/lib/python3.8/site-packages/web_cache/__init__.py", line 374, in run
    cache_obj = WebCache(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/web_cache/__init__.py", line 75, in __init__
    self.__connection.executescript("""PRAGMA journal_mode = MEMORY;
sqlite3.DatabaseError: database disk image is malformed
Exception ignored in: <function WebCache.__del__ at 0x7f4b43395940>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/web_cache/__init__.py", line 132, in __del__
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139961225016896 and this is thread id 139961259226368.

**Comment by desbma** [comment]
> sqlite3.DatabaseError: database disk image is malformed

Try removing the cache directory: `rm -R ~/.cache/google_speech`

**Comment by pavvel1610** [comment]
@desbma Thank you a lot for the response, your solution worked for me. In the future when I will see such error I will be aware of it.

**Comment by desbma** [comment]
It should never happen in the normal case, that can only occur when the program or your computer crashes while it is writing to the cache file.

**Comment by pavvel1610** [comment]
Now everything is clear, few days ago my OS crashed.
